string name
string value
bool keep_alive         # True -> keep the component running when chaning the parameter, False -> deactivate, change parameter then activate
---
bool success
string error_msg
